Adds iterative and optimized iterative comparisons
vc1492a/mieda pull request #5
Opened 2019-12-20 21:20 UTC by RyanStonebraker

This PR introduces two algorithms for comparison:
- Iterative - **O(n<sup>2</sup>)**
  - Uses two nested loops to search for conflicts to split
- Optimized Iterative - **O(n log n)**
  -  Uses pre-sorting and starts inner loop at next index

In addition to the new comparative algorithms, the PR updates the speed profiling jupyter notebook to include comparisons between all three algorithms.

2020-01-13 03:16 UTC, vc1492a commented
@RyanStonebraker any updates on your PR?

2020-02-07 21:38 UTC, vc1492a requested changes

2020-02-07 21:38 UTC, vc1492a commented on comparisons/iterative.py
> +def createInterval(start, finish, keys, key):
Please change case to match: `create_interval`

2020-02-07 21:38 UTC, vc1492a commented on comparisons/iterative.py
> +def getMainPermutations(intervals, key):
Please change case to match: `get_main_permutations`

2020-02-07 21:38 UTC, vc1492a commented on comparisons/iterative.py
> +def resolveConflicts(intervals, key):
Please change case to match: `resolve_conflicts`

2020-02-07 21:38 UTC, vc1492a commented on tests/test_merge_iterative_optimized.py
> +from comparisons.iterative_optimized import Merge
An import error exists here and results in tests failing, see: https://travis-ci.org/vc1492a/mieda/builds/646609867

2020-02-07 21:49 UTC, vc1492a commented
Thanks @RyanStonebraker for updating your PR, the changes look like a great start! If you could please address the above changes before merge, that would be great. 

I checked out the updated speed profiling notebook as well, and appreciate the additional plots and comparisons.

2020-02-07 21:54 UTC, RyanStonebraker commented
https://github.com/vc1492a/mieda/pull/5/commits/35513542aa374507550e5a71a5d66bd9b7cea377 (commit Renames functions to conform to snake case) <- should address the function renaming to match snake case. Also I just pushed an update to the test cases to import the renamed interval_balancing approach!

2020-02-07 23:52 UTC, vc1492a approved these changes

2020-02-11 17:14 UTC, merged